package com.sabayride.rental.booking;

import jakarta.persistence.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * The heart of the system.
 *
 * Note what is NOT mapped here:
 *   - `period` is a GENERATED ALWAYS column in PostgreSQL, derived from
 *     start_date and end_date. Mapping it as writable would make every insert
 *     fail with "cannot insert into generated column". It is the column the
 *     no_double_booking EXCLUDE constraint compares.
 */
@Entity
@Table(name = "booking")
public class Booking {

    @Id
    @GeneratedValue
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * SR-000128 — generated by a database DEFAULT from a sequence, so it is
     * read back after insert rather than written by us.
     */
    @Generated(event = EventType.INSERT)
    @Column(name = "reference", insertable = false, updatable = false, length = 20)
    private String reference;

    /** identity.users.id — no FK, different service. */
    @Column(name = "customer_id", nullable = false)
    private UUID customerId;

    /**
     * SNAPSHOT of the customer, copied at creation, so rendering a booking never
     * calls identity-service. Same principle as the price snapshot, applied to
     * the service boundary — a booking still renders when identity is down.
     */
    @Column(name = "customer_name", nullable = false, length = 120)
    private String customerName;

    @Column(name = "customer_phone", length = 20)
    private String customerPhone;

    @Column(name = "shop_id", nullable = false)
    private UUID shopId;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private BookingStatus status = BookingStatus.PENDING;

    /** INCLUSIVE. A LocalDate, not an Instant — a rental day is a calendar day. */
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /** EXCLUSIVE. 05 -> 07 is two days. */
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    /** The unit locked at creation. */
    @Column(name = "assigned_motorbike_id", nullable = false)
    private UUID assignedMotorbikeId;

    @Enumerated(EnumType.STRING)
    @Column(name = "pickup_method", nullable = false, length = 20)
    private PickupMethod pickupMethod;

    @Column(name = "delivery_address")
    private String deliveryAddress;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_option", nullable = false, length = 20)
    private PaymentOption paymentOption;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false, length = 30)
    private PaymentStatus paymentStatus = PaymentStatus.UNPAID;

    @Enumerated(EnumType.STRING)
    @Column(name = "payout_status", nullable = false, length = 20)
    private PayoutStatus payoutStatus = PayoutStatus.NOT_DUE;

    @Column(name = "subtotal", nullable = false, precision = 10, scale = 2)
    private BigDecimal subtotal;

    @Column(name = "delivery_fee", nullable = false, precision = 10, scale = 2)
    private BigDecimal deliveryFee = BigDecimal.ZERO;

    @Column(name = "total", nullable = false, precision = 10, scale = 2)
    private BigDecimal total;

    @Column(name = "currency", nullable = false, length = 3)
    private String currency = "USD";

    /** SNAPSHOT. Raising the platform rate later must not rewrite past bookings. */
    @Column(name = "commission_rate", nullable = false, precision = 5, scale = 4)
    private BigDecimal commissionRate;

    @Column(name = "platform_fee", nullable = false, precision = 10, scale = 2)
    private BigDecimal platformFee;

    @Column(name = "shop_payout", nullable = false, precision = 10, scale = 2)
    private BigDecimal shopPayout;

    @Column(name = "late_fee", nullable = false, precision = 10, scale = 2)
    private BigDecimal lateFee = BigDecimal.ZERO;

    @Column(name = "damage_fee", nullable = false, precision = 10, scale = 2)
    private BigDecimal damageFee = BigDecimal.ZERO;

    @Column(name = "refund_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal refundAmount = BigDecimal.ZERO;

    /** 30 min for a same-day pickup, 2 h otherwise. A sweep job expires these. */
    @Column(name = "hold_expires_at")
    private Instant holdExpiresAt;

    @Column(name = "confirmed_at")  private Instant confirmedAt;
    @Column(name = "activated_at")  private Instant activatedAt;
    @Column(name = "completed_at")  private Instant completedAt;

    @Column(name = "customer_note", length = 500)
    private String customerNote;

    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private Instant createdAt;

    protected Booking() { }

    public static Booking create(UUID customerId, String customerName, UUID shopId,
                                 LocalDate startDate, LocalDate endDate,
                                 UUID assignedMotorbikeId,
                                 PickupMethod pickupMethod, PaymentOption paymentOption,
                                 BigDecimal subtotal, BigDecimal deliveryFee,
                                 BigDecimal commissionRate, Instant holdExpiresAt) {
        Booking b = new Booking();
        b.customerId = customerId;
        b.customerName = customerName;
        b.shopId = shopId;
        b.startDate = startDate;
        b.endDate = endDate;
        b.assignedMotorbikeId = assignedMotorbikeId;
        b.pickupMethod = pickupMethod;
        b.paymentOption = paymentOption;
        b.subtotal = subtotal;
        b.deliveryFee = deliveryFee;
        b.total = subtotal.add(deliveryFee);
        b.commissionRate = commissionRate;
        // Commission is on the RENTAL only. The delivery fee reimburses the shop
        // for petrol and labour — taking a cut would make delivery loss-making.
        b.platformFee = subtotal.multiply(commissionRate)
                                .setScale(2, java.math.RoundingMode.HALF_UP);
        b.shopPayout = b.total.subtract(b.platformFee);
        b.holdExpiresAt = holdExpiresAt;
        return b;
    }

    public int rentalDays() {
        return (int) java.time.temporal.ChronoUnit.DAYS.between(startDate, endDate);
    }

    public UUID getId() { return id; }
    public String getReference() { return reference; }
    public UUID getCustomerId() { return customerId; }
    public String getCustomerName() { return customerName; }
    public String getCustomerPhone() { return customerPhone; }
    public void setCustomerPhone(String v) { this.customerPhone = v; }
    public UUID getShopId() { return shopId; }
    public BookingStatus getStatus() { return status; }
    public void setStatus(BookingStatus s) { this.status = s; }
    public LocalDate getStartDate() { return startDate; }
    public LocalDate getEndDate() { return endDate; }
    public UUID getAssignedMotorbikeId() { return assignedMotorbikeId; }
    public PickupMethod getPickupMethod() { return pickupMethod; }
    public String getDeliveryAddress() { return deliveryAddress; }
    public void setDeliveryAddress(String v) { this.deliveryAddress = v; }
    public PaymentOption getPaymentOption() { return paymentOption; }
    public PaymentStatus getPaymentStatus() { return paymentStatus; }
    public void setPaymentStatus(PaymentStatus v) { this.paymentStatus = v; }
    public PayoutStatus getPayoutStatus() { return payoutStatus; }
    public BigDecimal getSubtotal() { return subtotal; }
    public BigDecimal getDeliveryFee() { return deliveryFee; }
    public BigDecimal getTotal() { return total; }
    public String getCurrency() { return currency; }
    public BigDecimal getCommissionRate() { return commissionRate; }
    public BigDecimal getPlatformFee() { return platformFee; }
    public BigDecimal getShopPayout() { return shopPayout; }
    public Instant getHoldExpiresAt() { return holdExpiresAt; }
    public void setHoldExpiresAt(Instant v) { this.holdExpiresAt = v; }
    public Instant getConfirmedAt() { return confirmedAt; }
    public void setConfirmedAt(Instant v) { this.confirmedAt = v; }
    public String getCustomerNote() { return customerNote; }
    public void setCustomerNote(String v) { this.customerNote = v; }
    public Instant getCreatedAt() { return createdAt; }
}
